import type { KeyId } from '../keys';
import {
    KeyVRHmdOrientationW, KeyVRHmdOrientationX, KeyVRHmdOrientationY, KeyVRHmdOrientationZ,
    KeyVRHmdPositionX, KeyVRHmdPositionY, KeyVRHmdPositionZ,
    KeyVRLeftAxis0_N, KeyVRLeftAxis0_P, KeyVRLeftAxis1_N, KeyVRLeftAxis1_P, KeyVRLeftAxis2_N, KeyVRLeftAxis2_P, KeyVRLeftAxis3_N, KeyVRLeftAxis3_P,
    KeyVRLeftBtn0, KeyVRLeftBtn1, KeyVRLeftBtn2, KeyVRLeftBtn3, KeyVRLeftBtn4, KeyVRLeftBtn5,
    KeyVRLeftOrientationW, KeyVRLeftOrientationX, KeyVRLeftOrientationY, KeyVRLeftOrientationZ,
    KeyVRLeftPositionX, KeyVRLeftPositionY, KeyVRLeftPositionZ,
    KeyVRRightAxis0_N, KeyVRRightAxis0_P, KeyVRRightAxis1_N, KeyVRRightAxis1_P, KeyVRRightAxis2_N, KeyVRRightAxis2_P, KeyVRRightAxis3_N, KeyVRRightAxis3_P,
    KeyVRRightBtn0, KeyVRRightBtn1, KeyVRRightBtn2, KeyVRRightBtn3, KeyVRRightBtn4, KeyVRRightBtn5,
    KeyVRRightOrientationW, KeyVRRightOrientationX, KeyVRRightOrientationY, KeyVRRightOrientationZ,
    KeyVRRightPositionX, KeyVRRightPositionY, KeyVRRightPositionZ
} from './keys';

/**
 * Maps internal `KeyId` numeric constants for VR to their string names (without the "Key" prefix).
 * Useful for debugging or UI purposes.
 */
export const vrKeyMap: { readonly [keyId: KeyId]: string } = {
    [KeyVRHmdPositionX]: 'VRHmdPositionX',
    [KeyVRHmdPositionY]: 'VRHmdPositionY',
    [KeyVRHmdPositionZ]: 'VRHmdPositionZ',
    [KeyVRHmdOrientationX]: 'VRHmdOrientationX',
    [KeyVRHmdOrientationY]: 'VRHmdOrientationY',
    [KeyVRHmdOrientationZ]: 'VRHmdOrientationZ',
    [KeyVRHmdOrientationW]: 'VRHmdOrientationW',
    [KeyVRLeftPositionX]: 'VRLeftPositionX',
    [KeyVRLeftPositionY]: 'VRLeftPositionY',
    [KeyVRLeftPositionZ]: 'VRLeftPositionZ',
    [KeyVRLeftOrientationX]: 'VRLeftOrientationX',
    [KeyVRLeftOrientationY]: 'VRLeftOrientationY',
    [KeyVRLeftOrientationZ]: 'VRLeftOrientationZ',
    [KeyVRLeftOrientationW]: 'VRLeftOrientationW',
    [KeyVRLeftBtn0]: 'VRLeftBtn0',
    [KeyVRLeftBtn1]: 'VRLeftBtn1',
    [KeyVRLeftBtn2]: 'VRLeftBtn2',
    [KeyVRLeftBtn3]: 'VRLeftBtn3',
    [KeyVRLeftBtn4]: 'VRLeftBtn4',
    [KeyVRLeftBtn5]: 'VRLeftBtn5',
    [KeyVRLeftAxis0_P]: 'VRLeftAxis0_P',
    [KeyVRLeftAxis0_N]: 'VRLeftAxis0_N',
    [KeyVRLeftAxis1_P]: 'VRLeftAxis1_P',
    [KeyVRLeftAxis1_N]: 'VRLeftAxis1_N',
    [KeyVRLeftAxis2_P]: 'VRLeftAxis2_P',
    [KeyVRLeftAxis2_N]: 'VRLeftAxis2_N',
    [KeyVRLeftAxis3_P]: 'VRLeftAxis3_P',
    [KeyVRLeftAxis3_N]: 'VRLeftAxis3_N',
    [KeyVRRightPositionX]: 'VRRightPositionX',
    [KeyVRRightPositionY]: 'VRRightPositionY',
    [KeyVRRightPositionZ]: 'VRRightPositionZ',
    [KeyVRRightOrientationX]: 'VRRightOrientationX',
    [KeyVRRightOrientationY]: 'VRRightOrientationY',
    [KeyVRRightOrientationZ]: 'VRRightOrientationZ',
    [KeyVRRightOrientationW]: 'VRRightOrientationW',
    [KeyVRRightBtn0]: 'VRRightBtn0',
    [KeyVRRightBtn1]: 'VRRightBtn1',
    [KeyVRRightBtn2]: 'VRRightBtn2',
    [KeyVRRightBtn3]: 'VRRightBtn3',
    [KeyVRRightBtn4]: 'VRRightBtn4',
    [KeyVRRightBtn5]: 'VRRightBtn5',
    [KeyVRRightAxis0_P]: 'VRRightAxis0_P',
    [KeyVRRightAxis0_N]: 'VRRightAxis0_N',
    [KeyVRRightAxis1_P]: 'VRRightAxis1_P',
    [KeyVRRightAxis1_N]: 'VRRightAxis1_N',
    [KeyVRRightAxis2_P]: 'VRRightAxis2_P',
    [KeyVRRightAxis2_N]: 'VRRightAxis2_N',
    [KeyVRRightAxis3_P]: 'VRRightAxis3_P',
    [KeyVRRightAxis3_N]: 'VRRightAxis3_N',
};